### ISSUE TITLE
Problème

### ISSUE THREAD

**Issue by ImNeow** [Jarodbf/Projet_C_F1#4]
Pas de main.c , pas très professionnel ^^ 🤦‍♂️

**Comment by 4zv4l** [comment]
pareil, c'est vraiment dommage... 😒

**Comment by 4zv4l** [comment]
# PAS DE MAIN !!!
> oksour

**Comment by ImNeow** [comment]
** _Tellement de potentiel gaché par un simple oublie_**

**Comment by 4zv4l** [comment]
```c
#include <stdio.h>
int main(void){
  int m = fopen("main.c", "r");
  fclose(m);
}
```
# et voila main.c !

**Comment by ImNeow** [comment]
Quel homme 😍

**Comment by 4zv4l** [comment]
# MAIN.C
## manquant
> dommage...

**Comment by Jarodbf** [comment]
Bonjour,
j'ai créé une nouvelle branche ou vos remarque ont été prisent en consideration.
